# Generated by Django 3.2.9 on 2022-02-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='Story', max_length=32),
        ),
        migrations.AddField(
            model_name='post',
            name='editor',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
