# Generated by Django 3.2.9 on 2022-02-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editor',
            field=models.CharField(default='True', max_length=255),
        ),
    ]
